name: Github Actions Pipeline

on:
  push:
    tags:
      - "**prod-deploy-*"

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::905418370160:role/ProdAdminRole
          aws-region: eu-west-2

      - name: Terraform Setup & Apply
        run: |
          terraform fmt -check
          terraform init -backend-config=backend/backend_config_prod.tfvars
          terraform plan -no-color -var-file env.tfvars
          terraform apply -auto-approve -var-file env.tfvars